version: "3"

services:
    influxdb:
        build: docker_images/influxdb
        ports:
        - 8090:8090
        volumes:
        - ./shares/influxdb_share:/var/lib/influxdb
        command: -config /etc/influxdb/influxdb.conf

    ogamma-logger:
        build: docker_images/ogamma-logger
        ports:
        - 8091:8091
        volumes:
        - ./shares/ogamma-logger_share:/home/ogamma/logger/data
        links:
        - influxdb

    grafana:
        image: grafana/grafana
        environment:
        - GF_SERVER_HTTP_PORT=8092
        ports:
        - 8092:8092
        links:
        - influxdb
        depends_on:
        - ogamma-logger
